# This ingress will only run for PR environments
{{ if and .Values.pr.number .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pr-{{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.externalHost }}
    http:
      paths:
      - pathType: Prefix
        path: /pr{{ .Values.pr.number }}(/|$)(.*)
        backend:
          service:
            name: stitch
            port:
              name: "http"
{{- end -}}
