apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotned-saturday-23.fullname" . }}
  labels:
    {{- include "dotned-saturday-23.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dotned-saturday-23.selectorLabels" . | nindent 4 }}
