# Declare variables to be passed into your templates.
replicaCount: 1

image:
  name: viyacr.azurecr.io/dotned-saturday-23
  pullPolicy: Always
  tag: "0.0.1+replaced.by.yq.in.pipeline"

ingress:
  enabled: true
  externalHost: 'dotned.uranus.viya.me'

pr: # User for pull request deployments
  number: '' # set only in PR builds
  headSha: '' # set only in PR builds
  repoName: dotned-saturday-23
